server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_essentials?useSSL=false
    userName: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
